import os

SERVER_ENDPOINT = os.environ.get("SERVER_ENDPOINT", None)
MONGO_HOST = os.environ.get("MONGO_HOST", None)
MONGO_PORT = os.environ.get("MONGO_PORT", None)
MONGO_URI = os.environ.get("MONGO_URI", None)
MONGO_USERNAME = os.environ.get("MONGO_USERNAME", None)
MONGO_PASSWORD = os.environ.get("MONGO_PASSWORD", None)
DB_NAME = os.environ.get("DB_NAME", None)
JWT_SECRET = os.environ.get("JWT_SECRET", None)
EMAIL_ADDRESS = os.environ.get("EMAIL_ADDRESS", None)
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD", None)
EMAIL_SMTP_SERVER = os.environ.get("EMAIL_SMTP_SERVER", None)
OMDB_API_KEY = os.environ.get("OMDB_API_KEY", None)
TMDB_API_KEY = os.environ.get("TMDB_API_KEY", None)