version: '3'
  services:
    moviecheck:
      build: .
      env_file:
        - .env 
      container_name: moviecheck
      image: moviecheck
      restart: unless-stopped
      ports:
        - "8080:8080"
      volumes:
        - .:/app
      depends_on:
        - db
      networks:
        - frontend
        - backend

    db:
      image: postgres
      restart: always
      container_name: moviecheck-db
      environment:
        - "POSTGRES_USER=${POSTGRES_USERNAME}"
        - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        - "POSTGRES_DB=${DB_NAME}"
      volumes:
        - moviecheck_db:/var/lib/postgresql/data
      networks:
        - backend

volumes:
  moviecheck_db:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
